import type { EmployeeType } from "./employeeTypes";

export const employees: EmployeeType[] = [
    {
        id: "1",
        name: "Aria",
        email: "aria@corp.io",
        phone: "9876543210",
        role: "Senior Engineer",
        department: "SWE",
        salary: 120000,
        status: "active",
        joinedDate: "2021-03-01",
    },
    {
        id: "2",
        name: "Jordan",
        email: "jordan@corp.io",
        phone: "9123456780",
        role: "Engineering Manager",
        department: "Engineering",
        salary: 145000,
        status: "inactive",
        joinedDate: "2019-11-10",
    },
    {
        id: "3",
        name: "Chris",
        email: "chris@corp.io",
        phone: "9988776655",
        role: "Frontend Developer",
        department: "UI/UX",
        salary: 95000,
        status: "active",
        joinedDate: "2022-06-14",
    },
    {
        id: "4",
        name: "Yash",
        email: "yash@corp.io",
        phone: "9090909090",
        role: "Backend Developer",
        department: "SWE",
        salary: 105000,
        status: "active",
        joinedDate: "2020-01-25",
    },
    {
        id: "5",
        name: "Meera",
        email: "meera@corp.io",
        phone: "9812345678",
        role: "Data Engineer",
        department: "Data Engineering",
        salary: 115000,
        status: "active",
        joinedDate: "2021-09-08",
    },
    {
        id: "6",
        name: "Rohan",
        email: "rohan@corp.io",
        phone: "9765432109",
        role: "DevOps Engineer",
        department: "Cloud",
        salary: 125000,
        status: "inactive",
        joinedDate: "2018-04-19",
    },
    {
        id: "7",
        name: "Sana",
        email: "sana@corp.io",
        phone: "9345678123",
        role: "AI Engineer",
        department: "AI Engineering",
        salary: 135000,
        status: "active",
        joinedDate: "2023-02-12",
    },
    {
        id: "8",
        name: "Vikram",
        email: "vikram@corp.io",
        phone: "9234567891",
        role: "ML Engineer",
        department: "ML Engineering",
        salary: 140000,
        status: "active",
        joinedDate: "2020-10-05",
    },
    {
        id: "9",
        name: "Ananya",
        email: "ananya@corp.io",
        phone: "9898989898",
        role: "Product Manager",
        department: "Product",
        salary: 150000,
        status: "inactive",
        joinedDate: "2017-08-22",
    },
    {
        id: "10",
        name: "Kabir",
        email: "kabir@corp.io",
        phone: "9012345678",
        role: "QA Engineer",
        department: "Testing",
        salary: 85000,
        status: "active",
        joinedDate: "2022-11-01",
    },
    {
        id: "11",
        name: "Isha",
        email: "isha@corp.io",
        phone: "9556677889",
        role: "UI Designer",
        department: "UI/UX",
        salary: 90000,
        status: "active",
        joinedDate: "2021-05-17",
    },
    {
        id: "12",
        name: "Neeraj",
        email: "neeraj@corp.io",
        phone: "9445566778",
        role: "Security Analyst",
        department: "Cybersecurity",
        salary: 130000,
        status: "inactive",
        joinedDate: "2019-02-28",
    },
    {
        id: "13",
        name: "Priya",
        email: "priya@corp.io",
        phone: "9334455667",
        role: "Business Analyst",
        department: "Business",
        salary: 98000,
        status: "active",
        joinedDate: "2020-07-11",
    },
    {
        id: "14",
        name: "Aman",
        email: "aman@corp.io",
        phone: "9223344556",
        role: "Cloud Architect",
        department: "Cloud",
        salary: 160000,
        status: "active",
        joinedDate: "2016-12-09",
    },
    {
        id: "15",
        name: "Divya",
        email: "divya@corp.io",
        phone: "9112233445",
        role: "HR Executive",
        department: "HR",
        salary: 75000,
        status: "active",
        joinedDate: "2023-07-20",
    },
];